kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  image: mozaman/kind-worker:v1.24.0
# the three workers
- role: worker
  image: mozaman/kind-worker:v1.24.0
- role: worker
  image: mozaman/kind-worker:v1.24.0
- role: worker
  image: mozaman/kind-worker:v1.24.0
- role: worker
  image: mozaman/kind-worker:v1.24.0
